#!/usr/bin/env python3
"""Generate docs/functions.md: a complete index of every callable in Ago —
prelude functions, Rust builtins, and the `.x()` magic cast methods — with a
one-line description and where the source lives. Run from the repo root:

    python3 docs/gen_function_index.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PRELUDE = ROOT / "stdlib" / "prelude.ago"
RUST_SRC = ROOT / "src" / "rust" / "src"
OUT = ROOT / "docs" / "functions.md"

# Cast targets, mirrored from src/AgoSemanticChecker.ENDING_TO_TYPE.
CAST_SUFFIXES = {
    "a": "int", "ae": "float", "am": "bool", "aem": "int[]", "arum": "float[]",
    "as": "bool[]", "erum": "string[]", "es": "string", "uum": "any[]",
    "u": "map/struct", "e": "range", "ium": "any", "i": "null", "o": "function",
}

# The Rust functions exported as Ago builtins (mirrors AgoLsp._BUILTINS).
BUILTINS = [
    "dici", "audies", "species", "apertu", "scribi", "exei", "aequalam",
    "ordina", "literes", "exemplium", "claverum", "valuum", "misceu",
    "congruam", "congruum", "get", "set", "inseri", "removium",
]


def prelude_functions():
    out = []
    doc = []
    lines = PRELUDE.read_text().split("\n")
    for i, line in enumerate(lines):
        s = line.strip()
        if s.startswith("#"):
            doc.append(s.lstrip("#").strip())
            continue
        m = re.match(r"des\s+([A-Za-z_][A-Za-z_0-9]*)\s*\((.*?)\)", line)
        if m:
            out.append((m.group(1), m.group(2), " ".join(doc).strip(), i + 1))
        if s:
            doc = []
    return out


def rust_doc_and_loc(name):
    fn_re = re.compile(r"^\s*pub fn (" + re.escape(name) + r")\s*[(<]")
    for rs in sorted(RUST_SRC.glob("*.rs")):
        lines = rs.read_text().split("\n")
        for i, line in enumerate(lines):
            if fn_re.match(line):
                doc = []
                j = i - 1
                while j >= 0:
                    t = lines[j].strip()
                    if t.startswith("///"):
                        doc.append(t[3:].strip())
                    elif t.startswith("//"):
                        doc.append(t[2:].strip())
                    elif t.startswith("#["):
                        pass
                    else:
                        break
                    j -= 1
                return " ".join(reversed(doc)).strip(), f"src/rust/src/{rs.name}:{i + 1}"
    return "", ""


def main():
    md = []
    md.append("# Ago function index\n")
    md.append(
        "Every callable in Ago, with where its source lives. Auto-generated by "
        "`docs/gen_function_index.py` — do not edit by hand.\n"
    )
    md.append(
        "Ago infers a value's type from a variable's **ending** (`-a` int, `-ae` "
        "float, `-es` string, `-uum` any-list, `-u` map, ...). The same endings "
        "drive the cast methods below.\n"
    )

    # 1. Cast / conversion magic methods
    md.append("## Cast methods (`.x()`)\n")
    md.append(
        "Any value can be converted to another type by calling the method named "
        "for the target ending, e.g. `xa.es()` → string, `luum.a()` → length. "
        "Implemented by `AgoType::as_type` in `src/rust/src/casting.rs`.\n"
    )
    md.append("| method | target type |")
    md.append("|---|---|")
    for suf, ty in sorted(CAST_SUFFIXES.items()):
        md.append(f"| `.{suf}()` | {ty} |")
    md.append("")

    # 2. Rust builtins
    md.append("## Builtins (Rust runtime)\n")
    md.append("Always in scope. Source: `src/rust/src/`.\n")
    md.append("| function | description | source |")
    md.append("|---|---|---|")
    for name in sorted(BUILTINS):
        doc, loc = rust_doc_and_loc(name)
        md.append(f"| `{name}` | {doc or '—'} | `{loc}` |")
    md.append("")

    # 3. Prelude functions
    md.append("## Prelude (written in Ago)\n")
    md.append(
        "Standard library written in Ago itself, prepended to every program. "
        "Source: `stdlib/prelude.ago`. Names beginning with `_` are internal "
        "helpers.\n"
    )
    md.append("| function | description | source |")
    md.append("|---|---|---|")
    for name, params, doc, ln in prelude_functions():
        sig = f"{name}({params})"
        md.append(f"| `{sig}` | {doc or '—'} | `stdlib/prelude.ago:{ln}` |")
    md.append("")

    OUT.write_text("\n".join(md) + "\n")
    print(f"wrote {OUT} ({len(prelude_functions())} prelude, {len(BUILTINS)} builtins)")


if __name__ == "__main__":
    main()
